export const weeks = [
  {
    week: 1, phase: 1,
    title: "UX Foundations",
    focus: "UX vs UI, design thinking, usability, heuristics, user needs, problem framing, basic accessibility.",
    color: "from-indigo-500 to-indigo-600",
    accentColor: "#7c6fff",
    learn: [
      "Design thinking: empathize → define → ideate → prototype → test",
      "Usability heuristics and how they show up in real interfaces",
      "User-centered design and why it matters more than aesthetics",
      "Key terms: wireframes, personas, user flows, affordance, feedback",
      "Accessibility basics for inclusive, usable design",
    ],
    terms: ["Design Thinking","Usability Heuristics","Wireframes","Prototypes","Personas","User Flows","Information Architecture","Accessibility","User-centered Design","Task Flow","Pain Points","Affordance","Feedback","Consistency","Visual Hierarchy"],
    howToStudy: "Don't just read definitions. For each term: write a simple meaning in your own words, find one real app that uses it well, note where the concept appears in the interface, write one sentence on why it matters.",
    exercise: "Choose two websites or apps you already use. Tear them down like a designer: What is the main task? What feels easy or confusing? What seems visually strong or weak? What would you improve?",
    build: ["Personal glossary of key UX terms in your own words","Two full website/app teardowns","A mind map connecting all concepts"],
    output: "A clean understanding of the field and a personal vocabulary list",
    videos: [
      { title: "UX Design for Beginners – Full Course", channel: "Flux Academy", url: "https://www.youtube.com/results?search_query=UX+Design+for+Beginners+Full+Course+Flux+Academy" },
      { title: "What is Design Thinking?", channel: "IDEO U", url: "https://www.youtube.com/results?search_query=What+is+Design+Thinking+IDEO" },
      { title: "UX Design Kya Hota Hai? Hindi mein", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=UX+Design+Hindi+Beginners" },
    ],
  },
  {
    week: 2, phase: 1,
    title: "Figma Fundamentals + Layout",
    focus: "Frames, grids, alignment, spacing, components, variants, auto layout, typography, color basics.",
    color: "from-indigo-500 to-orange-500",
    accentColor: "#a855f7",
    learn: ["Frames, sections, constraints, and auto layout","Grids and column systems for consistent layouts","Components, variants, and design system thinking","Typography and color styles in Figma","Prototyping links between screens"],
    howToStudy: "Don't watch tutorials passively. Watch → Recreate from scratch → Change the layout once → Build one additional screen using the same logic.",
    exercise: "Recreate 3–5 screens from a real website: header, hero, CTA, card layout, form section, footer. The goal is training your eye, not publishing copies.",
    build: ["3–5 recreated screens with proper spacing","Components and color styles organized","A basic design system started"],
    output: "A better Figma workflow and visual discipline",
    videos: [
      { title: "Figma UI Design Tutorial – Get Started in 24 Minutes", channel: "AJ&Smart", url: "https://www.youtube.com/results?search_query=AJ+Smart+Figma+UI+Design+Tutorial+24+Minutes" },
      { title: "Figma Auto Layout – Complete Guide", channel: "Mizko", url: "https://www.youtube.com/results?search_query=Figma+Auto+Layout+Complete+Guide+Mizko" },
      { title: "Figma Complete Basics Tutorial Hindi – Class 01", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=Figma+Complete+Basics+Tutorial+Hindi" },
    ],
  },
  {
    week: 3, phase: 1,
    title: "Inspiration Study",
    focus: "How to study references from Mobbin, Awwwards, Siteinspire, Land-book, and Dribbble with purpose.",
    color: "from-orange-500 to-orange-500",
    accentColor: "#ec4899",
    learn: ["How to use inspiration platforms purposefully, not as wallpaper","Recognizing visual patterns and reusable design solutions","Building a swipe file organized by section type","Writing notes on why a design works"],
    howToStudy: "Save designs based on one question: Does this solve the same kind of problem I may need to solve? Create folders: Hero sections, Navigation, Pricing, Cards, Forms, Testimonials, Footers.",
    exercise: "For each saved design write: Why it works, What problem it solves, What idea can be reused, What should NOT be copied blindly.",
    build: ["Organized swipe file by section type","Recreate 2 inspired sections without directly copying","Pattern notes for each saved design"],
    output: "A reference library and a stronger eye for quality",
    videos: [
      { title: "How to Study UI Design Like a Pro", channel: "DesignCourse", url: "https://www.youtube.com/results?search_query=How+to+Study+UI+Design+DesignCourse" },
      { title: "Building a Swipe File for UI/UX Designers", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Building+Swipe+File+UI+UX+Designers" },
      { title: "Design Inspiration Kaise Lein – Hindi", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=UI+UX+Design+Inspiration+Hindi" },
    ],
  },
  {
    week: 4, phase: 2,
    title: "Pick Niches + Define a Project",
    focus: "How to choose a product niche, define a user problem, and write a clear problem statement.",
    color: "from-orange-500 to-orange-500",
    accentColor: "#f97316",
    learn: ["What makes a niche good for a beginner portfolio","How to write a clear problem statement","How to define target users and their goals","What content sections a website needs"],
    howToStudy: "The best niche: feels interesting enough to keep working on, has enough content to design, is not too complex for a beginner, can show a clear before/after or user flow, looks good in a portfolio.",
    exercise: "For each niche write: Who is the user? What problem does the site solve? What action should the user take? What content sections will it need? What makes it useful and believable?",
    build: ["Two niche briefs with full answers","One niche chosen for Project 1","One niche reserved for Project 2"],
    output: "Two project directions and a clear design problem",
    videos: [
      { title: "How to Write a UX Problem Statement", channel: "YouTube", url: "https://www.youtube.com/results?search_query=How+to+Write+UX+Problem+Statement" },
      { title: "Choosing Your UX Portfolio Project", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Choosing+UX+Portfolio+Project+Niche" },
      { title: "Project Brief Kaise Banate Hain – Hindi", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=UX+Project+Brief+Hindi" },
    ],
  },
  {
    week: 5, phase: 2,
    title: "Research + Structure",
    focus: "Personas, user journeys, user flows, information architecture, card sorting, competitive analysis.",
    color: "from-orange-500 to-yellow-500",
    accentColor: "#f59e0b",
    learn: ["How to create a realistic persona from a user profile","User journey mapping from first visit to final action","Sitemaps: what pages a website needs","User flows: the exact path from entry to conversion","Wireframing: rough structure without visual polish"],
    howToStudy: "Start with the user. Ask: Who is this for? What are they trying to do? What stops them? What do they need to see first? Then build structure before any visuals.",
    exercise: "Important rule: DO NOT start with colors, fonts, or fancy visuals. Start with structure.",
    build: ["One persona for your chosen niche","User journey map and sitemap","User flow diagram","Low-fidelity wireframes for main screens"],
    output: "Project 1 starts to feel real and UX-driven",
    videos: [
      { title: "How to Create a User Persona – Full Tutorial", channel: "CareerFoundry", url: "https://www.youtube.com/results?search_query=How+to+Create+User+Persona+CareerFoundry" },
      { title: "User Journey Mapping Explained", channel: "NNgroup", url: "https://www.youtube.com/results?search_query=User+Journey+Mapping+NNgroup" },
      { title: "UX Research Methods Hindi – Part 1", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=UX+Research+Methods+Hindi" },
    ],
  },
  {
    week: 6, phase: 2,
    title: "Low-fi to Mid-fi Design",
    focus: "Wireframes, prototyping, feedback loops, heuristic evaluation, accessibility checks.",
    color: "from-lime-500 to-teal-500",
    accentColor: "#84cc16",
    learn: ["What mid-fidelity design should and shouldn't show","How to build a clickable prototype in Figma","How to run a basic usability test with real people","What to observe vs what to ask during testing"],
    howToStudy: "Mid-fi shows: layout, content structure, button placement, form placement, navigation, relative importance of sections. Still keep it simple — no heavy color or decoration yet.",
    exercise: "Test with 3–5 people. Ask them to: find the pricing section, book a class, sign up, browse a product, contact the business. Watch: where they pause, what they miss, where they hesitate.",
    build: ["Cleaner mid-fidelity screens","Clickable prototype in Figma","Notes from 3–5 user tests"],
    output: "A testable early version of Project 1",
    videos: [
      { title: "How to Create Wireframes in Figma", channel: "YouTube", url: "https://www.youtube.com/results?search_query=How+to+Create+Wireframes+Figma+Tutorial" },
      { title: "Figma Prototyping – Complete Beginner Guide", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Figma+Prototyping+Beginner+Guide" },
      { title: "Wireframe Kya Hota Hai – Hindi UX Terms", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=What+is+wireframe+Hindi+UX+terms" },
    ],
  },
  {
    week: 7, phase: 2,
    title: "High-Fidelity Polish",
    focus: "Visual hierarchy, spacing rhythm, color system, components, UI consistency, empty states, microcopy.",
    color: "from-teal-500 to-teal-500",
    accentColor: "#22c55e",
    learn: ["Typography system with clear hierarchy","Color palette with intention: brand, feedback, hierarchy","Component consistency across all screens","Empty states, hover states, and form states","Responsive behavior and layout thinking"],
    howToStudy: "Think in systems: same button styles, consistent spacing values, one font hierarchy, reuse components, make sections feel connected. A polished UI is about clarity, confidence, and consistency — not just beauty.",
    exercise: "Focus areas: typography, color palette, spacing consistency, button styles, image treatment, component consistency, shadows, empty states, hover states, form states, responsive behavior.",
    build: ["Final high-fidelity UI for Project 1","Responsive variants for mobile and desktop","A polished component library"],
    output: "A portfolio-ready case study project",
    videos: [
      { title: "UI Design: Visual Hierarchy & Spacing", channel: "DesignCourse", url: "https://www.youtube.com/results?search_query=UI+Design+Visual+Hierarchy+Spacing+DesignCourse" },
      { title: "Building a Design System in Figma", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Building+Design+System+Figma+Tutorial" },
      { title: "Figma Design System Hindi – What is Design System", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=Figma+Design+System+Hindi" },
    ],
  },
  {
    week: 8, phase: 3,
    title: "AI Tools in Workflow",
    focus: "Figma AI / Make, Framer AI, Uizard, Maze, ChatGPT integrated into the design workflow.",
    color: "from-teal-500 to-teal-500",
    accentColor: "#14b8a6",
    learn: ["Figma AI for layout generation and rapid iteration","Framer AI for building publishable pages fast","Uizard for quick editable mockups from prompts","Maze for usability testing and card sorting","ChatGPT for research, personas, copy, and case studies"],
    howToStudy: "Use AI after you've thought on your own first. Sketch the idea manually → ask AI for 5 alternatives → select one → refine in Figma. The portfolio shows your thinking, not just the tool output.",
    exercise: "Take one page from Project 1, use one AI tool on a part of the process. Document: what AI gave you, what you changed, why your version is stronger.",
    build: ["Documented AI experiment with before/after","2–3 AI tools explored and understood","A clearer, faster personal workflow"],
    output: "A faster workflow and proof you can use modern tools",
    videos: [
      { title: "Figma AI Tutorial for Beginners", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Figma+AI+Tutorial+Beginners+2024" },
      { title: "Framer AI – Build a Website in Minutes", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Framer+AI+Build+Website+Tutorial" },
      { title: "ChatGPT for UI UX Designers – Hindi", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=ChatGPT+for+UI+UX+Designers+Hindi" },
    ],
  },
  {
    week: 9, phase: 3,
    title: "Project 2: Different Niche",
    focus: "How to transfer design patterns into a new context without making clones.",
    color: "from-teal-500 to-indigo-500",
    accentColor: "#06b6d4",
    learn: ["How to adapt your process to a new type of problem","What makes each niche visually and structurally unique","Avoiding clone syndrome: different audience, style, task flow"],
    howToStudy: "If Project 1 is a fitness website, Project 2 could be a boutique e-commerce site. Different: audience, visual style, task flow, content structure, business goal.",
    exercise: "Apply the same full process: research → persona → user flow → wireframes → mid-fi → high-fi. Show you can adapt, not just repeat.",
    build: ["Second project concept fully defined","Wireframes and initial screens","Evidence of a different design approach"],
    output: "A second portfolio project showing range",
    videos: [
      { title: "UI UX Case Study – Full Process Walkthrough", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UI+UX+Case+Study+Full+Process+Walkthrough" },
      { title: "How to Design for Different Niches", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UI+UX+Design+Different+Niche+Portfolio" },
      { title: "UI UX Design Process Hindi Step by Step", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=UI+UX+Design+Process+Hindi" },
    ],
  },
  {
    week: 10, phase: 3,
    title: "Testing + Revision",
    focus: "Usability testing basics, task testing, first-click testing, note-taking, iteration.",
    color: "from-indigo-500 to-indigo-500",
    accentColor: "#3b82f6",
    learn: ["How to run a simple task-based usability test","What to look for: misclicks, delays, confusing labels, weak CTAs","How to document findings and prioritize fixes","How testing notes become powerful portfolio material"],
    howToStudy: "Test both projects, even if small. Ask: complete this task, what did you expect, where were you confused, what did you like visually, what felt unnecessary?",
    exercise: "Look for: misclicks, delays, confusing labels, weak CTA clarity, poor hierarchy, unclear navigation, friction in forms or flows.",
    build: ["Usability test notes for both projects","Final revisions applied to both projects","Documentation: issue → why it mattered → what changed → how it improved"],
    output: "Evidence of feedback-driven design",
    videos: [
      { title: "How to Run Usability Testing (with Maze)", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Usability+Testing+Maze+Tutorial" },
      { title: "Unmoderated vs Moderated Usability Testing", channel: "NNgroup", url: "https://www.youtube.com/results?search_query=Unmoderated+Moderated+Usability+Testing+NNgroup" },
      { title: "Usability Testing Hindi – UX Research", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=Usability+Testing+Hindi+UX+Research" },
    ],
  },
  {
    week: 11, phase: 4,
    title: "Portfolio Build",
    focus: "Case study structure, project storytelling, presentation hierarchy, resume and LinkedIn cleanup.",
    color: "from-indigo-500 to-indigo-500",
    accentColor: "#6366f1",
    learn: ["How to structure each case study for maximum impact","What makes a homepage scannable in 10–15 seconds","How to write about your process clearly and honestly","Resume and LinkedIn basics for design roles"],
    howToStudy: "Each case study: context, problem, role, constraints, research, inspiration, wireframes, iterations, final design, what changed after feedback, and what you learned.",
    exercise: "Homepage: one-line intro, 2 featured projects, short about, contact. Avoid: messy poster wall, too many fonts, hiding process behind only final screenshots.",
    build: ["Portfolio site or page with homepage","At least 2 complete case studies with visible process","Resume and LinkedIn updated"],
    output: "A professional-looking portfolio draft",
    videos: [
      { title: "How to Build Your UI/UX Portfolio in 2025", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UI+UX+Design+Portfolio+2025+Beginners" },
      { title: "Writing a UX Case Study That Gets You Hired", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Writing+UX+Case+Study+Gets+Hired" },
      { title: "Portfolio Website Figma Tutorial Hindi/Urdu", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=Portfolio+Website+Figma+Hindi+Urdu" },
    ],
  },
  {
    week: 12, phase: 4,
    title: "Application Week",
    focus: "How to present work, explain decisions, prepare for interviews, and apply with purpose.",
    color: "from-indigo-500 to-indigo-500",
    accentColor: "#8b5cf6",
    learn: ["How to explain design decisions clearly and confidently","What interviewers care about in portfolios","How to tailor outreach messages to specific companies","Common questions and how to answer with your project stories"],
    howToStudy: "A strong designer is not only someone who makes good screens — it's someone who can explain WHY the screens make sense.",
    exercise: "Apply to: UI/UX internships, product design internships, junior visual/UI roles, design apprenticeships, startup design roles, freelance beginner projects. Where: LinkedIn, company career pages, design communities.",
    build: ["Applications sent with tailored messages","3 project stories prepared: problem → process → outcome","Interview prep completed"],
    output: "A working portfolio plus active applications",
    videos: [
      { title: "UI/UX Interview Questions & Answers", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UI+UX+Interview+Questions+Answers+2024" },
      { title: "How to Present Your Portfolio in an Interview", channel: "YouTube", url: "https://www.youtube.com/results?search_query=How+to+Present+Portfolio+Design+Interview" },
      { title: "Design Interview Tips Hindi – Kaise Prepare Karein", channel: "Hindi Tutorial", url: "https://www.youtube.com/results?search_query=Design+Interview+Tips+Hindi" },
    ],
  },
];

export const phases = [
  { id: 1, name: "Foundation", weeks: "1–3", color: "from-indigo-500/20 to-indigo-500/10", border: "border-indigo-500/30", text: "text-indigo-400" },
  { id: 2, name: "Build", weeks: "4–7", color: "from-orange-500/20 to-orange-500/10", border: "border-orange-500/30", text: "text-orange-400" },
  { id: 3, name: "Expand", weeks: "8–10", color: "from-teal-500/20 to-indigo-500/10", border: "border-teal-500/30", text: "text-teal-400" },
  { id: 4, name: "Launch", weeks: "11–12", color: "from-indigo-500/20 to-indigo-500/10", border: "border-indigo-500/30", text: "text-indigo-400" },
];

export const theory = [
  { icon: "💡", name: "Design Thinking", body: "A practical problem-solving framework: empathize → define → ideate → prototype → test → implement. Keeps user needs at the center of every decision." },
  { icon: "📏", name: "Usability Heuristics", body: "Rules of thumb for better interface design. Key ones: visibility of system status, consistency and standards, error prevention, and recognition rather than recall." },
  { icon: "🗂️", name: "Information Architecture", body: "How content is organized so users can find things easily. Includes sitemaps, navigation structure, and labeling systems." },
  { icon: "🔀", name: "User Flows", body: "The path a user takes to complete a task. Maps every decision point from entry to conversion, revealing where friction hides." },
  { icon: "📐", name: "Wireframes", body: "Low-detail layouts that focus on structure, hierarchy, and flow — not colors or decoration. They're about communication, not aesthetics." },
  { icon: "🖱️", name: "Prototypes", body: "Interactive versions used to test ideas before final development. Can be low-fi (clickable wireframes) or high-fi (pixel-perfect screens)." },
  { icon: "👁️", name: "Visual Hierarchy", body: "How the eye is guided through a screen using size, contrast, spacing, and placement. The most important element should always be the most visually prominent." },
  { icon: "🔤", name: "Typography", body: "Choosing typefaces, sizes, weights, line height, and spacing so text is readable and expressive. A strong type system creates consistency and trust." },
  { icon: "🎨", name: "Color Systems", body: "Using color intentionally for brand identity, hierarchy, feedback states, and accessibility. Never use color as the only way to communicate information." },
  { icon: "🧩", name: "Design Systems", body: "Reusable components and patterns that keep designs consistent and efficient. Think buttons, forms, cards — built once, used everywhere." },
  { icon: "📱", name: "Responsive Design", body: "Designing for different screen sizes and states. Content should reflow and adapt without breaking the experience on any device." },
  { icon: "♿", name: "Accessibility", body: "Making design usable for more people, including those with visual, motor, or cognitive limitations. Good accessibility is simply good design." },
  { icon: "✨", name: "Microinteractions", body: "Small moments like hover states, loading indicators, toggles, and confirmations that improve clarity and make the interface feel alive and responsive." },
];

export const aiTools = [
  { icon: "🪄", name: "Figma AI / Make", color: "#7c6fff", bg: "rgba(124,111,255,0.1)", why: "Turns prompts into editable layouts, generates assets, rewrites text, moves you faster from idea to prototype.", how: "Use for early drafts, quick layout explorations, copy cleanup, and testing how different screen structures could work." },
  { icon: "⚡", name: "Framer AI", color: "#ff6fb0", bg: "rgba(255,111,176,0.1)", why: "Builds polished web pages quickly and turns design ideas into live sites with minimal code.", how: "Use when you want a portfolio website, landing page, or publishable case study page fast." },
  { icon: "🎨", name: "Uizard", color: "#6fffd4", bg: "rgba(111,255,212,0.1)", why: "Fast editable mockups and quick concept generation from prompts or rough sketches.", how: "Use in the early phase to test a few directions quickly before rebuilding properly in Figma." },
  { icon: "🧪", name: "Maze", color: "#ffb464", bg: "rgba(255,180,100,0.1)", why: "Product research and usability testing built for designers.", how: "Use to run quick task-based tests on prototypes, card sorting, or tree testing." },
  { icon: "🤖", name: "ChatGPT", color: "#a89fff", bg: "rgba(168,159,255,0.1)", why: "Brainstorming, persona drafts, UX writing, research synthesis, and portfolio copy.", how: "Use to structure notes, summarize feedback, and draft case study language that you then refine yourself." },
];

export const inspoSites = [
  { emoji: "📱", name: "Mobbin", url: "https://mobbin.com", desc: "Real product flows and UI patterns from shipped apps." },
  { emoji: "🏆", name: "Awwwards", url: "https://awwwards.com", desc: "High-end websites and strong interaction ideas." },
  { emoji: "✨", name: "Siteinspire", url: "https://siteinspire.com", desc: "Curated website examples with clean browsing." },
  { emoji: "📄", name: "Land-book", url: "https://land-book.com", desc: "Landing pages, pricing pages, and portfolio inspiration." },
  { emoji: "🎨", name: "Dribbble", url: "https://dribbble.com/tags/ui-ux-design", desc: "Style ideas and visual trends — use for hints, not UX truth." },
];

export const niches = [
  { emoji: "💪", name: "Fitness / Wellness", desc: "Coaching, classes, tracking, membership, or healthy habit journey.", best: true },
  { emoji: "🍕", name: "Food / Cafe", desc: "Restaurant, cafe, cloud kitchen, catering, or online ordering.", best: false },
  { emoji: "📚", name: "Ed-Tech", desc: "Course platform, coaching institute, bootcamp, or study app.", best: true },
  { emoji: "✂️", name: "Local Services", desc: "Salon, clinic, dentist, repair service, or home services.", best: false },
  { emoji: "👗", name: "Boutique E-Commerce", desc: "Fashion, handcrafted products, skincare, or lifestyle brand.", best: true },
  { emoji: "🌿", name: "Beauty / Salon", desc: "Appointment booking, service menus, and client experience.", best: false },
  { emoji: "🏡", name: "Small Business", desc: "Any local brand needing a clear, effective online presence.", best: false },
  { emoji: "👤", name: "Personal Portfolio", desc: "Design for yourself — teaches you to present your own work clearly.", best: true },
];

export const caseStudySteps = [
  "Overview", "Problem Statement", "Target User & Context",
  "Research & Inspiration", "Process & Wireframes", "Design Exploration",
  "Final Screens", "Testing & Iteration", "Outcome", "Lessons Learned",
];

export const weeklyTargets = [
  "Glossary, notes, and two website teardowns",
  "Three recreated UI screens with proper spacing and alignment",
  "A swipe file and a pattern library",
  "Two niche briefs and one chosen project direction",
  "Persona, journey map, sitemap, and user flow",
  "Wireframes and a clickable prototype",
  "High-fidelity screens and a responsive version",
  "AI-assisted iteration and testing notes",
  "Second project concept and initial screens",
  "Tested and revised project versions",
  "Portfolio pages and case study drafts",
  "Final portfolio and active applications",
];

export const terms = [
  { label: "UX",                type: 1, url: "https://www.interaction-design.org/literature/topics/ux-design" },
  { label: "UI",                type: 1, url: "https://www.interaction-design.org/literature/topics/ui-design" },
  { label: "Product Design",    type: 2, url: "https://www.interaction-design.org/literature/topics/product-design" },
  { label: "Interaction Design",type: 2, url: "https://www.interaction-design.org/literature/topics/interaction-design" },
  { label: "Visual Hierarchy",  type: 1, url: "https://www.interaction-design.org/literature/topics/visual-hierarchy" },
  { label: "CTA",               type: 3, url: "https://en.wikipedia.org/wiki/Call_to_action_(marketing)" },
  { label: "Affordance",        type: 1, url: "https://www.interaction-design.org/literature/topics/affordances" },
  { label: "Feedback",          type: 2, url: "https://www.nngroup.com/articles/ten-usability-heuristics/" },
  { label: "Friction",          type: 3, url: "https://www.interaction-design.org/literature/topics/usability" },
  { label: "Conversion",        type: 3, url: "https://en.wikipedia.org/wiki/Conversion_rate_optimization" },
  { label: "Consistency",       type: 1, url: "https://www.nngroup.com/articles/ten-usability-heuristics/" },
  { label: "Responsiveness",    type: 2, url: "https://www.interaction-design.org/literature/topics/responsive-design" },
  { label: "Breakpoints",       type: 2, url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries" },
  { label: "Spacing Scale",     type: 1, url: "https://www.youtube.com/results?search_query=spacing+scale+8pt+grid+ui+design+system" },
  { label: "8-Point Grid",      type: 3, url: "https://www.youtube.com/results?search_query=8+point+grid+system+ui+design+explained" },
  { label: "Container",         type: 2, url: "https://www.youtube.com/results?search_query=container+layout+ui+ux+design+grid" },
  { label: "Section",           type: 2, url: "https://www.interaction-design.org/literature/topics/information-architecture" },
  { label: "Persona",           type: 1, url: "https://www.interaction-design.org/literature/topics/user-personas" },
  { label: "User Journey",      type: 2, url: "https://www.nngroup.com/articles/customer-journey-mapping/" },
  { label: "Sitemap",           type: 3, url: "https://www.interaction-design.org/literature/topics/information-architecture" },
  { label: "Wireframe",         type: 1, url: "https://www.interaction-design.org/literature/topics/wireframing" },
  { label: "Prototype",         type: 2, url: "https://www.interaction-design.org/literature/topics/prototyping" },
  { label: "Heuristic",         type: 3, url: "https://www.nngroup.com/articles/ten-usability-heuristics/" },
  { label: "Pain Points",       type: 1, url: "https://www.youtube.com/results?search_query=pain+points+ux+design+user+research" },
  { label: "Task Flow",         type: 2, url: "https://www.youtube.com/results?search_query=task+flow+vs+user+flow+ux+design" },
  { label: "Empty State",       type: 3, url: "https://www.youtube.com/results?search_query=empty+state+ux+ui+design+best+practices" },
  { label: "Microcopy",         type: 1, url: "https://www.youtube.com/results?search_query=microcopy+ux+writing+ui+design" },
  { label: "Design System",     type: 2, url: "https://www.interaction-design.org/literature/topics/design-systems" },
];

export const checklist = [
  { label: "Resume: one page, clean, focused on design skills and project outcomes", category: "Resume" },
  { label: "LinkedIn: updated headline, portfolio link, featured section, short about", category: "LinkedIn" },
  { label: "Portfolio: mobile-friendly, fast to load, scannable in 15 seconds", category: "Portfolio" },
  { label: "Case Study 1: problem, process, and outcome clearly shown", category: "Case Studies" },
  { label: "Case Study 2: different niche, showing range", category: "Case Studies" },
  { label: "Behance or Dribbble: only if work is strong enough to post", category: "Social" },
  { label: "Ready to explain design decisions, not just show screens", category: "Interview Prep" },
  { label: "Applications tailored — mention one specific reason the role fits", category: "Applications" },
  { label: "Outreach sent to designers and design communities", category: "Networking" },
  { label: "3 project stories prepared: problem → process → outcome", category: "Interview Prep" },
];

export const routine = [
  { day: "Mon", task: "Theory & notes" },
  { day: "Tue", task: "Watch tutorial + recreate one screen" },
  { day: "Wed", task: "Inspiration study + reference gathering" },
  { day: "Thu", task: "Build or refine the project" },
  { day: "Fri", task: "Apply feedback or improve case study" },
  { day: "Sat", task: "Deeper project work or testing" },
  { day: "Sun", task: "Review, rest, plan next week" },
];

export const youtubeLinks = {
  english: [
    { title: "Figma UI Design Tutorial: Get Started in Just 24 Minutes", channel: "AJ&Smart", url: "https://www.youtube.com/results?search_query=AJ+Smart+Figma+UI+Design+Tutorial+24+Minutes" },
    { title: "Figma AI Tutorial for Beginners", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Figma+AI+Tutorial+Beginners" },
    { title: "Figma Make Tutorial - Create an AI-Powered Prototype", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Figma+Make+Tutorial+AI+Prototype" },
    { title: "You need to know Usability Testing (with Maze)", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Usability+Testing+Maze" },
    { title: "How To Run a Design Thinking Workshop", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Design+Thinking+Workshop+Training" },
    { title: "How to build your first UI UX Design PORTFOLIO in 2025", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UI+UX+Design+Portfolio+2025" },
  ],
  hindi: [
    { title: "Figma Complete Basics Tutorial | Figma crash course Class 01", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Figma+Complete+Basics+Tutorial+Hindi" },
    { title: "UI/UX Design Process Step by Step (in Hindi)", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UI+UX+Design+Process+Hindi" },
    { title: "Learn UX Research Methods in Hindi | Part 1", channel: "YouTube", url: "https://www.youtube.com/results?search_query=UX+Research+Methods+Hindi" },
    { title: "Figma Design System in Hindi - What is Design System", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Figma+Design+System+Hindi" },
    { title: "Portfolio Website Design Tutorial in Figma - Hindi/Urdu", channel: "YouTube", url: "https://www.youtube.com/results?search_query=Portfolio+Website+Figma+Hindi+Urdu" },
    { title: "What is wireframe? in Hindi | UX terms | Ep-1", channel: "YouTube", url: "https://www.youtube.com/results?search_query=What+is+wireframe+Hindi+UX+terms" },
  ],
};
